# Generated by Django 4.2.1 on 2023-06-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counrty', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=128, null=True)),
            ],
        ),
    ]
