# Generated by Django 4.2.1 on 2023-06-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direction',
            old_name='counrty',
            new_name='country',
        ),
    ]
