# Generated by Django 4.2.1 on 2023-06-03 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direction.direction')),
            ],
        ),
    ]
