# Generated by Django 4.2.1 on 2023-06-03 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0002_rename_counrty_direction_country'),
        ('transporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporter',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transporters', to='direction.direction'),
        ),
    ]
