# Generated by Django 4.2.1 on 2023-06-03 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0002_rename_counrty_direction_country'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='arival_date',
            new_name='estimated_arrival_date',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='to_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='direction.direction'),
        ),
    ]
