# Generated by Django 4.2.1 on 2023-06-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_shipment_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='estimated_arrival_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sent_date',
            field=models.DateField(),
        ),
    ]
